version: "3.8"

services:
  postgres:
    container_name: indexer
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: indexer_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - indexer_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d indexer_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: indexer_pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5055:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - indexer_network

volumes:
  postgres_data:

networks:
  indexer_network:
    driver: bridge
